In [26]:
import json

import numpy as np
import pandas as pd

Primary Results Processing

In [27]:
with open("2016.primary.json") as fp:
    races = json.load(fp)

In [28]:
for idx, race in enumerate(races):
    print(f'{idx}:{race["race_id"]}')

0:mi-president-primary-republican-2016-03-08
1:mi-president-primary-democrat-2016-03-08

In [29]:
rep = races[0]
dem = races[1]

In [30]:
# Race to data frame for the 2016 Primary.
def race_to_df(race, party):
    data = list()
    for county in race["counties"]:
        row = dict()
        row["county"] = county["name"]
        total = 0
        for key, value in county["results"].items():
            row[f'prim_16_{key.split("-")[0]}'] = value
            total += value
        row[f"prim_16_{party}_total"] = total

        for key, value in county["results"].items():
            row[f'prim_16_{key.split("-")[0]}_pct'] = np.round(value / total, 4)

        data.append(row)
    return pd.DataFrame(data)

In [31]:
df_dem = race_to_df(dem, "dem")
df_rep = race_to_df(rep, "rep")

In [32]:
df = df_rep.merge(df_dem, on="county")

In [33]:
df

,county,prim_16_bush,prim_16_carson,prim_16_christie,prim_16_cruz,prim_16_fiorina,prim_16_graham,prim_16_huckabee,prim_16_kasich,prim_16_pataki,...,prim_16_de,prim_16_omalley,prim_16_sanders,prim_16_uncommitted_y,prim_16_dem_total,prim_16_clinton_pct,prim_16_de_pct,prim_16_omalley_pct,prim_16_sanders_pct,prim_16_uncommitted_pct_y
0,Alcona,13,27,5,460,4,0,2,340,2,...,1,5,455,26,950,0.4874,0.0011,0.0053,0.4789,0.0274
1,Alger,4,20,2,318,1,0,4,281,0,...,1,3,622,26,1036,0.3707,0.0010,0.0029,0.6004,0.0251
2,Allegan,164,362,36,7530,16,6,40,4636,6,...,8,8,5545,141,9191,0.3796,0.0009,0.0009,0.6033,0.0153
3,Alpena,24,60,8,1125,2,0,6,785,3,...,4,11,1347,26,2490,0.4426,0.0016,0.0044,0.5410,0.0104
4,Antrim,44,91,17,1201,5,4,10,1025,2,...,0,5,1491,39,2402,0.3609,0.0000,0.0021,0.6207,0.0162
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,Tuscola,67,163,27,2668,5,2,27,1268,5,...,3,14,2532,119,4652,0.4265,0.0006,0.0030,0.5443,0.0256
79,Van Buren,80,170,23,2579,9,2,17,2092,4,...,8,10,3656,94,6252,0.3973,0.0013,0.0016,0.5848,0.0150
80,Washtenaw,266,468,64,8574,35,14,67,12643,22,...,36,70,38063,506,68697,0.4370,0.0005,0.0010,0.5541,0.0074
81,Wayne,1046,1959,317,25155,166,61,250,38165,69,...,160,431,104999,3871,273347,0.5996,0.0006,0.0016,0.3841,0.0142
82,Wexford,30,98,10,1521,6,0,18,1060,0,...,5,9,1793,43,2759,0.3295,0.0018,0.0033,0.6499,0.0156

General Election

In [16]:
with open("2016.general.json") as fp:
    race2 = json.load(fp)

In [19]:
def race_to_df2(race):
    data = list()
    for county in race["counties"]:
        row = dict()
        row["county"] = county["name"]
        total = 0
        for key, value in county["results"].items():
            row[f'pres_16_{key.split("-")[0]}'] = value
            total += value
        row[f"pres_16_total"] = total

        for key, value in county["results"].items():
            row[f'pres_16_{key.split("-")[0]}_pct'] = np.round(value / total, 4)

        data.append(row)
    return pd.DataFrame(data)

In [21]:
df_gen = race_to_df2(race2)

In [23]:
df = df.merge(df_gen, on="county")

In [25]:
df.to_feather("2016.ft")